#ifndef ACHIEVEMENTS_H
#define ACHIEVEMENTS_H

enum AchievementsTypes
{
	ACHIEVEMENT_COMPLETE_ALL_LEVELS,
	ACHIEVEMENT_COMPLETE_LEVEL_WITHOUT_DAMAGE,
	COMPLETE_ALL_LEVELS_WITH_5_STARS,
	ACHIEVEMENT_KILL_100_CARS,
	ACHIEVEMENT_KILL_100_INFANTRY,
	ACHIEVEMENT_KILL_100_TRICYCLES,
	ACHIEVEMENT_KILL_100_SEFLHEAL,
	ACHIEVEMENT_KILL_100_ANOTHER,
	ACHIEVEMENT_KILL_100_TRACTORS,
	ACHIEVEMENT_KILL_100_SMALL,
	ACHIEVEMENT_KILL_50_TANKS,
	ACHIEVEMENT_KILL_50_SPIDERS,
	ACHIEVEMENT_KILL_50_MID,
	ACHIEVEMENT_KILL_50_SHIELD,
	ACHIEVEMENT_KILL_50_REPAIRS,
	ACHIEVEMENT_KILL_50_TELEPORTS,
	ACHIEVEMENT_KILL_10_BIGS,
	ACHIEVEMENT_KILL_10_BIG_TANK,
	ACHIEVEMENT_KILL_10_SPAWNS,
	ACHIEVEMENT_KILL_50_BY_TOWER,
	ACHIEVEMENT_KILL_100_BY_ACID,
	ACHIEVEMENT_KILL_5_BY_SINGLE_BOMB,
	ACHIEVEMENT_FREEZE_5_BY_SINGLE_BOMB,
	ACHIEVEMENT_DROP_DRAIN,
	ACHIEVEMENT_FULL_UPGRADE_ALL_TOWERS,
	ACHIEVEMENT_BUILD_100_TOWERS
};

enum StatsTypes
{
	STAT_CARS_KILLS,
	STAT_INFANTRY_KILLS,
	STAT_TRICYCLE_KILLS,
	STAT_SMALL_KILLS,
	STAT_ANOTHER_KILLS,
	STAT_SELFHEAL_KILLS2,
	STAT_TRACTOR_KILLS,
	STAT_TANK_KILLS,
	STAT_SPIDER_KILLS,
	STAT_MID_KILLS,
	STAT_REPAIR_KILLS,
	STAT_SHIELD_KILLS,
	STAT_TELEPORT_KILLS,
	STAT_BIG_KILLS,
	STAT_BIG_TANK_KILLS,
	STAT_SPAWN_KILLS,
	STAT_KILLS_BY_ACID,
	STAT_COMPLETED_LEVELS,
	STAT_5_STARS_COMPLETED_LEVELS,
	STAT_TOWER_MAX_KILLS,
	STAT_TOWERS_BUILDED
};

#endif // ACHIEVEMENTS_H
