#ifndef ACHIEVEMENTS_H
#define ACHIEVEMENTS_H

enum AchievementsTypes
{
	ACHIEVEMENT_COMPLETE_ALL_LEVELS,
	ACHIEVEMENT_COMPLETE_LEVEL_WITHOUT_DAMAGE,
	ACHIEVEMENT_KILL_100_CARS,



//	ACHIEVEMENT_COMPLETE_ALL_LEVELS_WITH_5_STARS,
//	ACHIEVEMENT_KILL_5_WITH_ONE_BOMB,
//	ACHIEVEMENT_FREEZE_5_WITH_ONE_BOMB,
//	ACHIEVEMENT_KILL_100_BY_ACID,
//	ACHIEVEMENT_KILL_10000_ENEMIES,
//	ACHIEVEMENT_KILL_100_BY_BASE_TOWER,
//	ACHIEVEMENT_KILL_100_BY_FREEZE_TOWER,
//	ACHIEVEMENT_KILL_100_BY_POWER_TOWER,
//	ACHIEVEMENT_KILL_100_BY_ROCKET_TOWER,
//	ACHIEVEMENT_KILL_100_BY_LASER_TOWER,
//	ACHIEVEMENT_KILL_100_BY_IMPROVED_TOWER
};

enum StatsTypes
{
	STAT_CARS_KILLS,
};

#endif // ACHIEVEMENTS_H
