#ifndef ACHIEVEMENTS_H
#define ACHIEVEMENTS_H

enum AchievementsTypes
{
	ACHIEVEMENT_COMPLETE_ALL_LEVELS,
	ACHIEVEMENT_COMPLETE_LEVEL_WITHOUT_DAMAGE,
	COMPLETE_ALL_LEVELS_WITH_5_STARS,
	ACHIEVEMENT_KILL_SMALL_ENEMIES,
	ACHIEVEMENT_KILL_MEDIUM_ENEMIES,
	ACHIEVEMENT_KILL_BIG_ENEMIES,
	ACHIEVEMENT_KILL_100_BY_TOWER,
	ACHIEVEMENT_KILL_100_BY_ACID,
	ACHIEVEMENT_KILL_5_BY_SINGLE_BOMB,
	ACHIEVEMENT_FREEZE_5_BY_SINGLE_BOMB,
	ACHIEVEMENT_DROP_DRAIN,
	ACHIEVEMENT_FULL_UPGRADE_ALL_TOWERS,
	ACHIEVEMENT_BUILD_1000_TOWERS,
	ACHIEVEMENT_COMPLETE_LEVEL_WITHOUT_ABILITIES,
	ACHIEVEMENT_COMPLETE_LEVEL_WITHOUT_TOWERS,
	ACHIEVEMENT_GAIN_MANY_MONEY,
	ACHIEVEMENT_SELL_INACTIVE_TOWER,
	ACHIEVEMENT_KILL_INVISIBLE,
};

enum StatsTypes
{
	STAT_SMALL_KILLS,
	STAT_MID_KILLS,
	STAT_BIG_KILLS,
	STAT_KILLS_BY_ACID,
	STAT_COMPLETED_LEVELS,
	STAT_5_STARS_COMPLETED_LEVELS,
	STAT_TOWERS_BUILDED,
	STAT_MONEY_GAINED,
};

#endif // ACHIEVEMENTS_H
