#ifndef TEXTURES_TYPES_H
#define TEXTURES_TYPES_H

namespace RESOURCES
{
enum TEXTURE_TYPE
{
	//ui
	PANEL_TEXTURE,
	CURSOR_TEXTURE,
	STAR_TEXTURE,
	EMPTY_STAR_TEXTURE,
	SELL_TEXTURE,
	UPGRADE_TEXTURE,
	GAME_MENU_TEXTURE,
	GAME_OVER_TEXTURE,
	MISSON_COMPLETED_TEXTURE,
	PANEL_CURSOR,
	HEALTH_ICON,
	ENERGY_ICON,
	MONEY_ICON,
	START_TEXTURE,
	END_TEXTURE,

	ABILITY_BOMB,
	ABILITY_FREEZE_BOMB,
	ABILITY_CARPET_BOMBING,
	ABILITY_INCREASE_TOWER_DAMAGE,
	ABILITY_INCREASE_TOWER_ATTACK_SPEED,
	ABILITY_TIME_STOP,

	TOWER_BASE,
	TOWER_POWER,
	TOWER_ROCKET,
	TOWER_FREEZE,
	TOWER_LASER,
	TOWER_IMPROVED,

	BASE_PROJECTILE,
	IMPROVED_PROJECTILE,
	ROCKET_PROJECTILE,
	FREEZE_PROJECTILE,
	LASER_PROJECTILE,

	ABOUT_BACKGROUND,
	SETTINGS_BACKGROUND,
	MENU_BACKGROUND,
	CLOSE_BACKGROUND,
	INTRO_BACKGROUND,

	EXPLOSION_EFFECT,
	VENOM_EFFECT,


	ENEMY_SCORPION,
	ENEMY_CAR,
	ENEMY_TRICYCLE,
	ENEMY_TANK,
	ENEMY_SPIDER,
	ENEMY_HELICOPTER,
	ENEMY_AIRCARRIER,
	ENEMY_BIG_TANK,
	ENEMY_PLANE
};
}

#endif // TEXTURES_TYPES_H
