#ifndef TEXTURES_TYPES_H
#define TEXTURES_TYPES_H

namespace RESOURCES
{
enum TEXTURE_TYPE
{
	PANEL_TEXTURE,
	CURSOR_TEXTURE,
	ENEMY_TEXTURE,

	ABILITY_BOMB,
	ABILITY_FREEZE_BOMB,
	ABILITY_CARPET_BOMBING,
	ABILITY_INCREASE_TOWER_DAMAGE,
	ABILITY_INCREASE_TOWER_ATTACK_SPEED,
	ABILITY_TIME_STOP,

	TOWER_BASE,
	TOWER_POWER,
	TOWER_ROCKET,
	TOWER_FREEZE,
	TOWER_SPLASH,
	TOWER_IMPROVED,


	GARAGE_BACKGROUND,
	ABOUT_BACKGROUND,
	SETTINGS_BACKGROUND,
	MENU_BACKGROUND,
	CLOSE_BACKGROUND,
	INTRO_BACKGROUND,
	PLANETS_BACKGROUND,

	EXPLOSION_EFFECT,
};
}

#endif // TEXTURES_TYPES_H
